import type { Router } from "express";

import authRoutes from "../modules/auth/routes/index.js";
import usersRoutes from "../modules/users/routes/index.js";
import rolesRoutes from "../modules/roles/routes/index.js";
import permissionsRoutes from "../modules/permissions/routes/index.js";
import countriesRoutes from "../modules/countries/routes/index.js";
import citiesRoutes from "../modules/cities/routes/index.js";
import investorsRoutes from "../modules/investors/routes/index.js";
import walletsRoutes from "../modules/wallets/routes/index.js";
import transactionsRoutes from "../modules/transactions/routes/index.js";
import notificationsRoutes from "../modules/notifications/routes/index.js";
import kycRoutes from "../modules/kyc/routes/index.js";
import paymentsRoutes from "../modules/payments/routes/index.js";
import landsRoutes from "../modules/lands/routes/index.js";
import projectsRoutes from "../modules/projects/routes/index.js";
import holdingsRoutes from "../modules/holdings/routes/index.js";
import marketplaceRoutes from "../modules/marketplace/routes/index.js";
import reportsRoutes from "../modules/reports/routes/index.js";
import supportRoutes from "../modules/support/routes/index.js";
import cmsRoutes from "../modules/cms/routes/index.js";
import adminRoutes from "../modules/admin/routes/index.js";
import superAdminRoutes from "../modules/super-admin/routes/index.js";
import goldRoutes from "../modules/gold/routes/index.js";
import sakRoutes from "../modules/sak/routes/index.js";
import marketRoutes from "../modules/market/routes/index.js";
import devRoutes from "../modules/dev/routes/index.js";
import auditRoutes from "../modules/audit/routes/index.js";
import publicRoutes from "../modules/public/routes/index.js";
import profileRoutes from "../modules/profile/routes/index.js";
import mediaRoutes from "../modules/media/routes/index.js";
import profitDistributionRoutes from "../modules/profit-distributions/routes/index.js";
import certificateRoutes from "../modules/certificates/routes/index.js";
import paymentMethodsRoutes from "../modules/payment-methods/routes/index.js";
import performanceRoutes from "../modules/performance/routes/index.js";
import affiliateRoutes from "../modules/affiliate/routes/index.js";
import leadsRoutes from "../modules/leads/routes/index.js";
import viewingsRoutes from "../modules/viewings/routes/index.js";
import bookingsRoutes from "../modules/bookings/routes/index.js";
import commissionsRoutes from "../modules/commissions/routes/index.js";
import brokersRoutes from "../modules/brokers/routes/index.js";
import investmentRequestsRoutes from "../modules/investment-requests/routes/index.js";

export function registerFeatureRoutes(v1Router: Router): void {
  v1Router.use("/auth", authRoutes);
  v1Router.use("/users", usersRoutes);
  v1Router.use("/roles", rolesRoutes);
  v1Router.use("/permissions", permissionsRoutes);
  v1Router.use("/countries", countriesRoutes);
  v1Router.use("/cities", citiesRoutes);
  v1Router.use("/investors", investorsRoutes);
  v1Router.use("/wallets", walletsRoutes);
  v1Router.use("/transactions", transactionsRoutes);
  v1Router.use("/notifications", notificationsRoutes);
  v1Router.use("/kyc", kycRoutes);
  v1Router.use("/payments", paymentsRoutes);
  v1Router.use("/lands", landsRoutes);
  v1Router.use("/projects", projectsRoutes);
  v1Router.use("/holdings", holdingsRoutes);
  v1Router.use("/marketplace", marketplaceRoutes);
  v1Router.use("/reports", reportsRoutes);
  v1Router.use("/support", supportRoutes);
  v1Router.use("/cms", cmsRoutes);
  v1Router.use("/admin", adminRoutes);
  v1Router.use("/super-admin", superAdminRoutes);
  v1Router.use("/gold", goldRoutes);
  v1Router.use("/sak", sakRoutes);
  v1Router.use("/market", marketRoutes);
  v1Router.use("/dev", devRoutes);
  v1Router.use("/audit", auditRoutes);
  v1Router.use("/public", publicRoutes);
  v1Router.use("/profile", profileRoutes);
  v1Router.use("/media", mediaRoutes);
  v1Router.use("/profit-distributions", profitDistributionRoutes);
  v1Router.use("/certificates", certificateRoutes);
  v1Router.use("/payment-methods", paymentMethodsRoutes);
  v1Router.use("/performance", performanceRoutes);
  v1Router.use("/affiliate", affiliateRoutes);
  v1Router.use("/leads", leadsRoutes);
  v1Router.use("/viewings", viewingsRoutes);
  v1Router.use("/bookings", bookingsRoutes);
  v1Router.use("/commissions", commissionsRoutes);
  v1Router.use("/brokers", brokersRoutes);
  v1Router.use("/investment-requests", investmentRequestsRoutes);
}
