/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetsLandIdRouteImport } from './routes/assets.$landId'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedKycRouteImport } from './routes/_authenticated/kyc'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminWithdrawalsRouteImport } from './routes/_authenticated/admin/withdrawals'
import { Route as AuthenticatedAdminLandsRouteImport } from './routes/_authenticated/admin/lands'
import { Route as AuthenticatedAdminKycRouteImport } from './routes/_authenticated/admin/kyc'
import { Route as AuthenticatedAdminInvestorsRouteImport } from './routes/_authenticated/admin/investors'
import { Route as AuthenticatedAdminDepositsRouteImport } from './routes/_authenticated/admin/deposits'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsLandIdRoute = AssetsLandIdRouteImport.update({
  id: '/assets/$landId',
  path: '/assets/$landId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKycRoute = AuthenticatedKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminWithdrawalsRoute =
  AuthenticatedAdminWithdrawalsRouteImport.update({
    id: '/withdrawals',
    path: '/withdrawals',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLandsRoute = AuthenticatedAdminLandsRouteImport.update({
  id: '/lands',
  path: '/lands',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminKycRoute = AuthenticatedAdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminInvestorsRoute =
  AuthenticatedAdminInvestorsRouteImport.update({
    id: '/investors',
    path: '/investors',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDepositsRoute =
  AuthenticatedAdminDepositsRouteImport.update({
    id: '/deposits',
    path: '/deposits',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kyc': typeof AuthenticatedKycRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/assets/$landId': typeof AssetsLandIdRoute
  '/admin/deposits': typeof AuthenticatedAdminDepositsRoute
  '/admin/investors': typeof AuthenticatedAdminInvestorsRoute
  '/admin/kyc': typeof AuthenticatedAdminKycRoute
  '/admin/lands': typeof AuthenticatedAdminLandsRoute
  '/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kyc': typeof AuthenticatedKycRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/assets/$landId': typeof AssetsLandIdRoute
  '/admin/deposits': typeof AuthenticatedAdminDepositsRoute
  '/admin/investors': typeof AuthenticatedAdminInvestorsRoute
  '/admin/kyc': typeof AuthenticatedAdminKycRoute
  '/admin/lands': typeof AuthenticatedAdminLandsRoute
  '/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/kyc': typeof AuthenticatedKycRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/assets/$landId': typeof AssetsLandIdRoute
  '/_authenticated/admin/deposits': typeof AuthenticatedAdminDepositsRoute
  '/_authenticated/admin/investors': typeof AuthenticatedAdminInvestorsRoute
  '/_authenticated/admin/kyc': typeof AuthenticatedAdminKycRoute
  '/_authenticated/admin/lands': typeof AuthenticatedAdminLandsRoute
  '/_authenticated/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/projects'
    | '/sitemap.xml'
    | '/admin'
    | '/dashboard'
    | '/kyc'
    | '/notifications'
    | '/portfolio'
    | '/transactions'
    | '/wallet'
    | '/assets/$landId'
    | '/admin/deposits'
    | '/admin/investors'
    | '/admin/kyc'
    | '/admin/lands'
    | '/admin/withdrawals'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/projects'
    | '/sitemap.xml'
    | '/dashboard'
    | '/kyc'
    | '/notifications'
    | '/portfolio'
    | '/transactions'
    | '/wallet'
    | '/assets/$landId'
    | '/admin/deposits'
    | '/admin/investors'
    | '/admin/kyc'
    | '/admin/lands'
    | '/admin/withdrawals'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/projects'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/kyc'
    | '/_authenticated/notifications'
    | '/_authenticated/portfolio'
    | '/_authenticated/transactions'
    | '/_authenticated/wallet'
    | '/assets/$landId'
    | '/_authenticated/admin/deposits'
    | '/_authenticated/admin/investors'
    | '/_authenticated/admin/kyc'
    | '/_authenticated/admin/lands'
    | '/_authenticated/admin/withdrawals'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ProjectsRoute: typeof ProjectsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AssetsLandIdRoute: typeof AssetsLandIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$landId': {
      id: '/assets/$landId'
      path: '/assets/$landId'
      fullPath: '/assets/$landId'
      preLoaderRoute: typeof AssetsLandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kyc': {
      id: '/_authenticated/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof AuthenticatedKycRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/withdrawals': {
      id: '/_authenticated/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AuthenticatedAdminWithdrawalsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/lands': {
      id: '/_authenticated/admin/lands'
      path: '/lands'
      fullPath: '/admin/lands'
      preLoaderRoute: typeof AuthenticatedAdminLandsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/kyc': {
      id: '/_authenticated/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AuthenticatedAdminKycRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/investors': {
      id: '/_authenticated/admin/investors'
      path: '/investors'
      fullPath: '/admin/investors'
      preLoaderRoute: typeof AuthenticatedAdminInvestorsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/deposits': {
      id: '/_authenticated/admin/deposits'
      path: '/deposits'
      fullPath: '/admin/deposits'
      preLoaderRoute: typeof AuthenticatedAdminDepositsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminDepositsRoute: typeof AuthenticatedAdminDepositsRoute
  AuthenticatedAdminInvestorsRoute: typeof AuthenticatedAdminInvestorsRoute
  AuthenticatedAdminKycRoute: typeof AuthenticatedAdminKycRoute
  AuthenticatedAdminLandsRoute: typeof AuthenticatedAdminLandsRoute
  AuthenticatedAdminWithdrawalsRoute: typeof AuthenticatedAdminWithdrawalsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminDepositsRoute: AuthenticatedAdminDepositsRoute,
    AuthenticatedAdminInvestorsRoute: AuthenticatedAdminInvestorsRoute,
    AuthenticatedAdminKycRoute: AuthenticatedAdminKycRoute,
    AuthenticatedAdminLandsRoute: AuthenticatedAdminLandsRoute,
    AuthenticatedAdminWithdrawalsRoute: AuthenticatedAdminWithdrawalsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKycRoute: typeof AuthenticatedKycRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKycRoute: AuthenticatedKycRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ProjectsRoute: ProjectsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AssetsLandIdRoute: AssetsLandIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
