/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BrokerRouteRouteImport } from './routes/broker/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrokerIndexRouteImport } from './routes/broker/index'
import { Route as BrokerViewingsRouteImport } from './routes/broker/viewings'
import { Route as BrokerReferralsRouteImport } from './routes/broker/referrals'
import { Route as BrokerProfileRouteImport } from './routes/broker/profile'
import { Route as BrokerLeadsRouteImport } from './routes/broker/leads'
import { Route as BrokerInvestmentRequestsRouteImport } from './routes/broker/investment-requests'
import { Route as BrokerCommissionsRouteImport } from './routes/broker/commissions'
import { Route as BrokerClientsRouteImport } from './routes/broker/clients'
import { Route as BrokerBookingsRouteImport } from './routes/broker/bookings'
import { Route as BrokerAnalyticsRouteImport } from './routes/broker/analytics'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AssetsLandIdRouteImport } from './routes/assets.$landId'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSakGoldRouteImport } from './routes/_authenticated/sak-gold'
import { Route as AuthenticatedSakBalanceRouteImport } from './routes/_authenticated/sak-balance'
import { Route as AuthenticatedRealAssetsRouteImport } from './routes/_authenticated/real-assets'
import { Route as AuthenticatedProfitsRouteImport } from './routes/_authenticated/profits'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'
import { Route as AuthenticatedPerformanceRouteImport } from './routes/_authenticated/performance'
import { Route as AuthenticatedPaymentMethodsRouteImport } from './routes/_authenticated/payment-methods'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedKycRouteImport } from './routes/_authenticated/kyc'
import { Route as AuthenticatedInvestmentRequestsRouteImport } from './routes/_authenticated/investment-requests'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConvertRouteImport } from './routes/_authenticated/convert'
import { Route as AuthenticatedCertificatesRouteImport } from './routes/_authenticated/certificates'
import { Route as AuthenticatedAssetAllocationRouteImport } from './routes/_authenticated/asset-allocation'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as BrokerLeadsLeadIdRouteImport } from './routes/broker/leads.$leadId'
import { Route as AuthenticatedInvestmentRequestsIdRouteImport } from './routes/_authenticated/investment-requests.$id'
import { Route as AuthenticatedAdminWithdrawalsRouteImport } from './routes/_authenticated/admin/withdrawals'
import { Route as AuthenticatedAdminWalletsRouteImport } from './routes/_authenticated/admin/wallets'
import { Route as AuthenticatedAdminTransactionsRouteImport } from './routes/_authenticated/admin/transactions'
import { Route as AuthenticatedAdminSakConfigRouteImport } from './routes/_authenticated/admin/sak-config'
import { Route as AuthenticatedAdminProjectsRouteImport } from './routes/_authenticated/admin/projects'
import { Route as AuthenticatedAdminProfitsRouteImport } from './routes/_authenticated/admin/profits'
import { Route as AuthenticatedAdminProfitHistoryRouteImport } from './routes/_authenticated/admin/profit-history'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminLandsRouteImport } from './routes/_authenticated/admin/lands'
import { Route as AuthenticatedAdminKycRouteImport } from './routes/_authenticated/admin/kyc'
import { Route as AuthenticatedAdminInvestorsRouteImport } from './routes/_authenticated/admin/investors'
import { Route as AuthenticatedAdminInvestmentRequestsRouteImport } from './routes/_authenticated/admin/investment-requests'
import { Route as AuthenticatedAdminHomepageRouteImport } from './routes/_authenticated/admin/homepage'
import { Route as AuthenticatedAdminGoldRouteImport } from './routes/_authenticated/admin/gold'
import { Route as AuthenticatedAdminDepositsRouteImport } from './routes/_authenticated/admin/deposits'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin/customers'
import { Route as AuthenticatedAdminCountriesRouteImport } from './routes/_authenticated/admin/countries'
import { Route as AuthenticatedAdminCommissionsRouteImport } from './routes/_authenticated/admin/commissions'
import { Route as AuthenticatedAdminCitiesRouteImport } from './routes/_authenticated/admin/cities'
import { Route as AuthenticatedAdminBrokersRouteImport } from './routes/_authenticated/admin/brokers'
import { Route as AuthenticatedAdminBrokerApplicationsRouteImport } from './routes/_authenticated/admin/broker-applications'
import { Route as AuthenticatedAdminAuditLogRouteImport } from './routes/_authenticated/admin/audit-log'
import { Route as AuthenticatedAdminAssetTypesRouteImport } from './routes/_authenticated/admin/asset-types'
import { Route as AuthenticatedInvestmentRequestsIdPaymentRouteImport } from './routes/_authenticated/investment-requests.$id.payment'
import { Route as AuthenticatedAdminInvestmentRequestsIdRouteImport } from './routes/_authenticated/admin/investment-requests.$id'
import { Route as AuthenticatedAdminCustomersIdRouteImport } from './routes/_authenticated/admin/customers.$id'
import { Route as AuthenticatedAdminBrokersIdRouteImport } from './routes/_authenticated/admin/brokers.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokerRouteRoute = BrokerRouteRouteImport.update({
  id: '/broker',
  path: '/broker',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokerIndexRoute = BrokerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrokerRouteRoute,
} as any)
const BrokerViewingsRoute = BrokerViewingsRouteImport.update({
  id: '/viewings',
  path: '/viewings',
  getParentRoute: () => BrokerRouteRoute,
} as any)
const BrokerReferralsRoute = BrokerReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => BrokerRouteRoute,
} as any)
const BrokerProfileRoute = BrokerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => BrokerRouteRoute,
} as any)
const BrokerLeadsRoute = BrokerLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => BrokerRouteRoute,
} as any)
const BrokerInvestmentRequestsRoute =
  BrokerInvestmentRequestsRouteImport.update({
    id: '/investment-requests',
    path: '/investment-requests',
    getParentRoute: () => BrokerRouteRoute,
  } as any)
const BrokerCommissionsRoute = BrokerCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => BrokerRouteRoute,
} as any)
const BrokerClientsRoute = BrokerClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => BrokerRouteRoute,
} as any)
const BrokerBookingsRoute = BrokerBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => BrokerRouteRoute,
} as any)
const BrokerAnalyticsRoute = BrokerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => BrokerRouteRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AssetsLandIdRoute = AssetsLandIdRouteImport.update({
  id: '/assets/$landId',
  path: '/assets/$landId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSakGoldRoute = AuthenticatedSakGoldRouteImport.update({
  id: '/sak-gold',
  path: '/sak-gold',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSakBalanceRoute = AuthenticatedSakBalanceRouteImport.update({
  id: '/sak-balance',
  path: '/sak-balance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRealAssetsRoute = AuthenticatedRealAssetsRouteImport.update({
  id: '/real-assets',
  path: '/real-assets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfitsRoute = AuthenticatedProfitsRouteImport.update({
  id: '/profits',
  path: '/profits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerformanceRoute =
  AuthenticatedPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentMethodsRoute =
  AuthenticatedPaymentMethodsRouteImport.update({
    id: '/payment-methods',
    path: '/payment-methods',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKycRoute = AuthenticatedKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvestmentRequestsRoute =
  AuthenticatedInvestmentRequestsRouteImport.update({
    id: '/investment-requests',
    path: '/investment-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConvertRoute = AuthenticatedConvertRouteImport.update({
  id: '/convert',
  path: '/convert',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificatesRoute =
  AuthenticatedCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssetAllocationRoute =
  AuthenticatedAssetAllocationRouteImport.update({
    id: '/asset-allocation',
    path: '/asset-allocation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const BrokerLeadsLeadIdRoute = BrokerLeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => BrokerLeadsRoute,
} as any)
const AuthenticatedInvestmentRequestsIdRoute =
  AuthenticatedInvestmentRequestsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedInvestmentRequestsRoute,
  } as any)
const AuthenticatedAdminWithdrawalsRoute =
  AuthenticatedAdminWithdrawalsRouteImport.update({
    id: '/withdrawals',
    path: '/withdrawals',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminWalletsRoute =
  AuthenticatedAdminWalletsRouteImport.update({
    id: '/wallets',
    path: '/wallets',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTransactionsRoute =
  AuthenticatedAdminTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSakConfigRoute =
  AuthenticatedAdminSakConfigRouteImport.update({
    id: '/sak-config',
    path: '/sak-config',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProjectsRoute =
  AuthenticatedAdminProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProfitsRoute =
  AuthenticatedAdminProfitsRouteImport.update({
    id: '/profits',
    path: '/profits',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProfitHistoryRoute =
  AuthenticatedAdminProfitHistoryRouteImport.update({
    id: '/profit-history',
    path: '/profit-history',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLandsRoute = AuthenticatedAdminLandsRouteImport.update({
  id: '/lands',
  path: '/lands',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminKycRoute = AuthenticatedAdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminInvestorsRoute =
  AuthenticatedAdminInvestorsRouteImport.update({
    id: '/investors',
    path: '/investors',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminInvestmentRequestsRoute =
  AuthenticatedAdminInvestmentRequestsRouteImport.update({
    id: '/investment-requests',
    path: '/investment-requests',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminHomepageRoute =
  AuthenticatedAdminHomepageRouteImport.update({
    id: '/homepage',
    path: '/homepage',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminGoldRoute = AuthenticatedAdminGoldRouteImport.update({
  id: '/gold',
  path: '/gold',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminDepositsRoute =
  AuthenticatedAdminDepositsRouteImport.update({
    id: '/deposits',
    path: '/deposits',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCountriesRoute =
  AuthenticatedAdminCountriesRouteImport.update({
    id: '/countries',
    path: '/countries',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCommissionsRoute =
  AuthenticatedAdminCommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCitiesRoute =
  AuthenticatedAdminCitiesRouteImport.update({
    id: '/cities',
    path: '/cities',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBrokersRoute =
  AuthenticatedAdminBrokersRouteImport.update({
    id: '/brokers',
    path: '/brokers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBrokerApplicationsRoute =
  AuthenticatedAdminBrokerApplicationsRouteImport.update({
    id: '/broker-applications',
    path: '/broker-applications',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditLogRoute =
  AuthenticatedAdminAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAssetTypesRoute =
  AuthenticatedAdminAssetTypesRouteImport.update({
    id: '/asset-types',
    path: '/asset-types',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedInvestmentRequestsIdPaymentRoute =
  AuthenticatedInvestmentRequestsIdPaymentRouteImport.update({
    id: '/payment',
    path: '/payment',
    getParentRoute: () => AuthenticatedInvestmentRequestsIdRoute,
  } as any)
const AuthenticatedAdminInvestmentRequestsIdRoute =
  AuthenticatedAdminInvestmentRequestsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminInvestmentRequestsRoute,
  } as any)
const AuthenticatedAdminCustomersIdRoute =
  AuthenticatedAdminCustomersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminCustomersRoute,
  } as any)
const AuthenticatedAdminBrokersIdRoute =
  AuthenticatedAdminBrokersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminBrokersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/broker': typeof BrokerRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/asset-allocation': typeof AuthenticatedAssetAllocationRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/convert': typeof AuthenticatedConvertRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/investment-requests': typeof AuthenticatedInvestmentRequestsRouteWithChildren
  '/kyc': typeof AuthenticatedKycRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/payment-methods': typeof AuthenticatedPaymentMethodsRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/profits': typeof AuthenticatedProfitsRoute
  '/real-assets': typeof AuthenticatedRealAssetsRoute
  '/sak-balance': typeof AuthenticatedSakBalanceRoute
  '/sak-gold': typeof AuthenticatedSakGoldRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/assets/$landId': typeof AssetsLandIdRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/broker/analytics': typeof BrokerAnalyticsRoute
  '/broker/bookings': typeof BrokerBookingsRoute
  '/broker/clients': typeof BrokerClientsRoute
  '/broker/commissions': typeof BrokerCommissionsRoute
  '/broker/investment-requests': typeof BrokerInvestmentRequestsRoute
  '/broker/leads': typeof BrokerLeadsRouteWithChildren
  '/broker/profile': typeof BrokerProfileRoute
  '/broker/referrals': typeof BrokerReferralsRoute
  '/broker/viewings': typeof BrokerViewingsRoute
  '/broker/': typeof BrokerIndexRoute
  '/admin/asset-types': typeof AuthenticatedAdminAssetTypesRoute
  '/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/admin/broker-applications': typeof AuthenticatedAdminBrokerApplicationsRoute
  '/admin/brokers': typeof AuthenticatedAdminBrokersRouteWithChildren
  '/admin/cities': typeof AuthenticatedAdminCitiesRoute
  '/admin/commissions': typeof AuthenticatedAdminCommissionsRoute
  '/admin/countries': typeof AuthenticatedAdminCountriesRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRouteWithChildren
  '/admin/deposits': typeof AuthenticatedAdminDepositsRoute
  '/admin/gold': typeof AuthenticatedAdminGoldRoute
  '/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/admin/investment-requests': typeof AuthenticatedAdminInvestmentRequestsRouteWithChildren
  '/admin/investors': typeof AuthenticatedAdminInvestorsRoute
  '/admin/kyc': typeof AuthenticatedAdminKycRoute
  '/admin/lands': typeof AuthenticatedAdminLandsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/profit-history': typeof AuthenticatedAdminProfitHistoryRoute
  '/admin/profits': typeof AuthenticatedAdminProfitsRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/sak-config': typeof AuthenticatedAdminSakConfigRoute
  '/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/admin/wallets': typeof AuthenticatedAdminWalletsRoute
  '/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/investment-requests/$id': typeof AuthenticatedInvestmentRequestsIdRouteWithChildren
  '/broker/leads/$leadId': typeof BrokerLeadsLeadIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/brokers/$id': typeof AuthenticatedAdminBrokersIdRoute
  '/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/admin/investment-requests/$id': typeof AuthenticatedAdminInvestmentRequestsIdRoute
  '/investment-requests/$id/payment': typeof AuthenticatedInvestmentRequestsIdPaymentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/asset-allocation': typeof AuthenticatedAssetAllocationRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/convert': typeof AuthenticatedConvertRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/investment-requests': typeof AuthenticatedInvestmentRequestsRouteWithChildren
  '/kyc': typeof AuthenticatedKycRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/payment-methods': typeof AuthenticatedPaymentMethodsRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/profits': typeof AuthenticatedProfitsRoute
  '/real-assets': typeof AuthenticatedRealAssetsRoute
  '/sak-balance': typeof AuthenticatedSakBalanceRoute
  '/sak-gold': typeof AuthenticatedSakGoldRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/assets/$landId': typeof AssetsLandIdRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/broker/analytics': typeof BrokerAnalyticsRoute
  '/broker/bookings': typeof BrokerBookingsRoute
  '/broker/clients': typeof BrokerClientsRoute
  '/broker/commissions': typeof BrokerCommissionsRoute
  '/broker/investment-requests': typeof BrokerInvestmentRequestsRoute
  '/broker/leads': typeof BrokerLeadsRouteWithChildren
  '/broker/profile': typeof BrokerProfileRoute
  '/broker/referrals': typeof BrokerReferralsRoute
  '/broker/viewings': typeof BrokerViewingsRoute
  '/broker': typeof BrokerIndexRoute
  '/admin/asset-types': typeof AuthenticatedAdminAssetTypesRoute
  '/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/admin/broker-applications': typeof AuthenticatedAdminBrokerApplicationsRoute
  '/admin/brokers': typeof AuthenticatedAdminBrokersRouteWithChildren
  '/admin/cities': typeof AuthenticatedAdminCitiesRoute
  '/admin/commissions': typeof AuthenticatedAdminCommissionsRoute
  '/admin/countries': typeof AuthenticatedAdminCountriesRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRouteWithChildren
  '/admin/deposits': typeof AuthenticatedAdminDepositsRoute
  '/admin/gold': typeof AuthenticatedAdminGoldRoute
  '/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/admin/investment-requests': typeof AuthenticatedAdminInvestmentRequestsRouteWithChildren
  '/admin/investors': typeof AuthenticatedAdminInvestorsRoute
  '/admin/kyc': typeof AuthenticatedAdminKycRoute
  '/admin/lands': typeof AuthenticatedAdminLandsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/profit-history': typeof AuthenticatedAdminProfitHistoryRoute
  '/admin/profits': typeof AuthenticatedAdminProfitsRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/sak-config': typeof AuthenticatedAdminSakConfigRoute
  '/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/admin/wallets': typeof AuthenticatedAdminWalletsRoute
  '/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/investment-requests/$id': typeof AuthenticatedInvestmentRequestsIdRouteWithChildren
  '/broker/leads/$leadId': typeof BrokerLeadsLeadIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/brokers/$id': typeof AuthenticatedAdminBrokersIdRoute
  '/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/admin/investment-requests/$id': typeof AuthenticatedAdminInvestmentRequestsIdRoute
  '/investment-requests/$id/payment': typeof AuthenticatedInvestmentRequestsIdPaymentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/broker': typeof BrokerRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/asset-allocation': typeof AuthenticatedAssetAllocationRoute
  '/_authenticated/certificates': typeof AuthenticatedCertificatesRoute
  '/_authenticated/convert': typeof AuthenticatedConvertRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/investment-requests': typeof AuthenticatedInvestmentRequestsRouteWithChildren
  '/_authenticated/kyc': typeof AuthenticatedKycRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/payment-methods': typeof AuthenticatedPaymentMethodsRoute
  '/_authenticated/performance': typeof AuthenticatedPerformanceRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
  '/_authenticated/profits': typeof AuthenticatedProfitsRoute
  '/_authenticated/real-assets': typeof AuthenticatedRealAssetsRoute
  '/_authenticated/sak-balance': typeof AuthenticatedSakBalanceRoute
  '/_authenticated/sak-gold': typeof AuthenticatedSakGoldRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/assets/$landId': typeof AssetsLandIdRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/broker/analytics': typeof BrokerAnalyticsRoute
  '/broker/bookings': typeof BrokerBookingsRoute
  '/broker/clients': typeof BrokerClientsRoute
  '/broker/commissions': typeof BrokerCommissionsRoute
  '/broker/investment-requests': typeof BrokerInvestmentRequestsRoute
  '/broker/leads': typeof BrokerLeadsRouteWithChildren
  '/broker/profile': typeof BrokerProfileRoute
  '/broker/referrals': typeof BrokerReferralsRoute
  '/broker/viewings': typeof BrokerViewingsRoute
  '/broker/': typeof BrokerIndexRoute
  '/_authenticated/admin/asset-types': typeof AuthenticatedAdminAssetTypesRoute
  '/_authenticated/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/_authenticated/admin/broker-applications': typeof AuthenticatedAdminBrokerApplicationsRoute
  '/_authenticated/admin/brokers': typeof AuthenticatedAdminBrokersRouteWithChildren
  '/_authenticated/admin/cities': typeof AuthenticatedAdminCitiesRoute
  '/_authenticated/admin/commissions': typeof AuthenticatedAdminCommissionsRoute
  '/_authenticated/admin/countries': typeof AuthenticatedAdminCountriesRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRouteWithChildren
  '/_authenticated/admin/deposits': typeof AuthenticatedAdminDepositsRoute
  '/_authenticated/admin/gold': typeof AuthenticatedAdminGoldRoute
  '/_authenticated/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/_authenticated/admin/investment-requests': typeof AuthenticatedAdminInvestmentRequestsRouteWithChildren
  '/_authenticated/admin/investors': typeof AuthenticatedAdminInvestorsRoute
  '/_authenticated/admin/kyc': typeof AuthenticatedAdminKycRoute
  '/_authenticated/admin/lands': typeof AuthenticatedAdminLandsRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/profit-history': typeof AuthenticatedAdminProfitHistoryRoute
  '/_authenticated/admin/profits': typeof AuthenticatedAdminProfitsRoute
  '/_authenticated/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/_authenticated/admin/sak-config': typeof AuthenticatedAdminSakConfigRoute
  '/_authenticated/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/_authenticated/admin/wallets': typeof AuthenticatedAdminWalletsRoute
  '/_authenticated/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/_authenticated/investment-requests/$id': typeof AuthenticatedInvestmentRequestsIdRouteWithChildren
  '/broker/leads/$leadId': typeof BrokerLeadsLeadIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/brokers/$id': typeof AuthenticatedAdminBrokersIdRoute
  '/_authenticated/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/_authenticated/admin/investment-requests/$id': typeof AuthenticatedAdminInvestmentRequestsIdRoute
  '/_authenticated/investment-requests/$id/payment': typeof AuthenticatedInvestmentRequestsIdPaymentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/broker'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/projects'
    | '/sitemap.xml'
    | '/admin'
    | '/asset-allocation'
    | '/certificates'
    | '/convert'
    | '/dashboard'
    | '/investment-requests'
    | '/kyc'
    | '/marketplace'
    | '/notifications'
    | '/payment-methods'
    | '/performance'
    | '/portfolio'
    | '/profits'
    | '/real-assets'
    | '/sak-balance'
    | '/sak-gold'
    | '/settings'
    | '/support'
    | '/transactions'
    | '/wallet'
    | '/assets/$landId'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/broker/analytics'
    | '/broker/bookings'
    | '/broker/clients'
    | '/broker/commissions'
    | '/broker/investment-requests'
    | '/broker/leads'
    | '/broker/profile'
    | '/broker/referrals'
    | '/broker/viewings'
    | '/broker/'
    | '/admin/asset-types'
    | '/admin/audit-log'
    | '/admin/broker-applications'
    | '/admin/brokers'
    | '/admin/cities'
    | '/admin/commissions'
    | '/admin/countries'
    | '/admin/customers'
    | '/admin/deposits'
    | '/admin/gold'
    | '/admin/homepage'
    | '/admin/investment-requests'
    | '/admin/investors'
    | '/admin/kyc'
    | '/admin/lands'
    | '/admin/notifications'
    | '/admin/profit-history'
    | '/admin/profits'
    | '/admin/projects'
    | '/admin/sak-config'
    | '/admin/transactions'
    | '/admin/wallets'
    | '/admin/withdrawals'
    | '/investment-requests/$id'
    | '/broker/leads/$leadId'
    | '/admin/'
    | '/admin/brokers/$id'
    | '/admin/customers/$id'
    | '/admin/investment-requests/$id'
    | '/investment-requests/$id/payment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/projects'
    | '/sitemap.xml'
    | '/asset-allocation'
    | '/certificates'
    | '/convert'
    | '/dashboard'
    | '/investment-requests'
    | '/kyc'
    | '/marketplace'
    | '/notifications'
    | '/payment-methods'
    | '/performance'
    | '/portfolio'
    | '/profits'
    | '/real-assets'
    | '/sak-balance'
    | '/sak-gold'
    | '/settings'
    | '/support'
    | '/transactions'
    | '/wallet'
    | '/assets/$landId'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/broker/analytics'
    | '/broker/bookings'
    | '/broker/clients'
    | '/broker/commissions'
    | '/broker/investment-requests'
    | '/broker/leads'
    | '/broker/profile'
    | '/broker/referrals'
    | '/broker/viewings'
    | '/broker'
    | '/admin/asset-types'
    | '/admin/audit-log'
    | '/admin/broker-applications'
    | '/admin/brokers'
    | '/admin/cities'
    | '/admin/commissions'
    | '/admin/countries'
    | '/admin/customers'
    | '/admin/deposits'
    | '/admin/gold'
    | '/admin/homepage'
    | '/admin/investment-requests'
    | '/admin/investors'
    | '/admin/kyc'
    | '/admin/lands'
    | '/admin/notifications'
    | '/admin/profit-history'
    | '/admin/profits'
    | '/admin/projects'
    | '/admin/sak-config'
    | '/admin/transactions'
    | '/admin/wallets'
    | '/admin/withdrawals'
    | '/investment-requests/$id'
    | '/broker/leads/$leadId'
    | '/admin'
    | '/admin/brokers/$id'
    | '/admin/customers/$id'
    | '/admin/investment-requests/$id'
    | '/investment-requests/$id/payment'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/broker'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/projects'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/asset-allocation'
    | '/_authenticated/certificates'
    | '/_authenticated/convert'
    | '/_authenticated/dashboard'
    | '/_authenticated/investment-requests'
    | '/_authenticated/kyc'
    | '/_authenticated/marketplace'
    | '/_authenticated/notifications'
    | '/_authenticated/payment-methods'
    | '/_authenticated/performance'
    | '/_authenticated/portfolio'
    | '/_authenticated/profits'
    | '/_authenticated/real-assets'
    | '/_authenticated/sak-balance'
    | '/_authenticated/sak-gold'
    | '/_authenticated/settings'
    | '/_authenticated/support'
    | '/_authenticated/transactions'
    | '/_authenticated/wallet'
    | '/assets/$landId'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/broker/analytics'
    | '/broker/bookings'
    | '/broker/clients'
    | '/broker/commissions'
    | '/broker/investment-requests'
    | '/broker/leads'
    | '/broker/profile'
    | '/broker/referrals'
    | '/broker/viewings'
    | '/broker/'
    | '/_authenticated/admin/asset-types'
    | '/_authenticated/admin/audit-log'
    | '/_authenticated/admin/broker-applications'
    | '/_authenticated/admin/brokers'
    | '/_authenticated/admin/cities'
    | '/_authenticated/admin/commissions'
    | '/_authenticated/admin/countries'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/deposits'
    | '/_authenticated/admin/gold'
    | '/_authenticated/admin/homepage'
    | '/_authenticated/admin/investment-requests'
    | '/_authenticated/admin/investors'
    | '/_authenticated/admin/kyc'
    | '/_authenticated/admin/lands'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/profit-history'
    | '/_authenticated/admin/profits'
    | '/_authenticated/admin/projects'
    | '/_authenticated/admin/sak-config'
    | '/_authenticated/admin/transactions'
    | '/_authenticated/admin/wallets'
    | '/_authenticated/admin/withdrawals'
    | '/_authenticated/investment-requests/$id'
    | '/broker/leads/$leadId'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/brokers/$id'
    | '/_authenticated/admin/customers/$id'
    | '/_authenticated/admin/investment-requests/$id'
    | '/_authenticated/investment-requests/$id/payment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  BrokerRouteRoute: typeof BrokerRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ProjectsRoute: typeof ProjectsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AssetsLandIdRoute: typeof AssetsLandIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broker': {
      id: '/broker'
      path: '/broker'
      fullPath: '/broker'
      preLoaderRoute: typeof BrokerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broker/': {
      id: '/broker/'
      path: '/'
      fullPath: '/broker/'
      preLoaderRoute: typeof BrokerIndexRouteImport
      parentRoute: typeof BrokerRouteRoute
    }
    '/broker/viewings': {
      id: '/broker/viewings'
      path: '/viewings'
      fullPath: '/broker/viewings'
      preLoaderRoute: typeof BrokerViewingsRouteImport
      parentRoute: typeof BrokerRouteRoute
    }
    '/broker/referrals': {
      id: '/broker/referrals'
      path: '/referrals'
      fullPath: '/broker/referrals'
      preLoaderRoute: typeof BrokerReferralsRouteImport
      parentRoute: typeof BrokerRouteRoute
    }
    '/broker/profile': {
      id: '/broker/profile'
      path: '/profile'
      fullPath: '/broker/profile'
      preLoaderRoute: typeof BrokerProfileRouteImport
      parentRoute: typeof BrokerRouteRoute
    }
    '/broker/leads': {
      id: '/broker/leads'
      path: '/leads'
      fullPath: '/broker/leads'
      preLoaderRoute: typeof BrokerLeadsRouteImport
      parentRoute: typeof BrokerRouteRoute
    }
    '/broker/investment-requests': {
      id: '/broker/investment-requests'
      path: '/investment-requests'
      fullPath: '/broker/investment-requests'
      preLoaderRoute: typeof BrokerInvestmentRequestsRouteImport
      parentRoute: typeof BrokerRouteRoute
    }
    '/broker/commissions': {
      id: '/broker/commissions'
      path: '/commissions'
      fullPath: '/broker/commissions'
      preLoaderRoute: typeof BrokerCommissionsRouteImport
      parentRoute: typeof BrokerRouteRoute
    }
    '/broker/clients': {
      id: '/broker/clients'
      path: '/clients'
      fullPath: '/broker/clients'
      preLoaderRoute: typeof BrokerClientsRouteImport
      parentRoute: typeof BrokerRouteRoute
    }
    '/broker/bookings': {
      id: '/broker/bookings'
      path: '/bookings'
      fullPath: '/broker/bookings'
      preLoaderRoute: typeof BrokerBookingsRouteImport
      parentRoute: typeof BrokerRouteRoute
    }
    '/broker/analytics': {
      id: '/broker/analytics'
      path: '/analytics'
      fullPath: '/broker/analytics'
      preLoaderRoute: typeof BrokerAnalyticsRouteImport
      parentRoute: typeof BrokerRouteRoute
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/assets/$landId': {
      id: '/assets/$landId'
      path: '/assets/$landId'
      fullPath: '/assets/$landId'
      preLoaderRoute: typeof AssetsLandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sak-gold': {
      id: '/_authenticated/sak-gold'
      path: '/sak-gold'
      fullPath: '/sak-gold'
      preLoaderRoute: typeof AuthenticatedSakGoldRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sak-balance': {
      id: '/_authenticated/sak-balance'
      path: '/sak-balance'
      fullPath: '/sak-balance'
      preLoaderRoute: typeof AuthenticatedSakBalanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/real-assets': {
      id: '/_authenticated/real-assets'
      path: '/real-assets'
      fullPath: '/real-assets'
      preLoaderRoute: typeof AuthenticatedRealAssetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profits': {
      id: '/_authenticated/profits'
      path: '/profits'
      fullPath: '/profits'
      preLoaderRoute: typeof AuthenticatedProfitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/performance': {
      id: '/_authenticated/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payment-methods': {
      id: '/_authenticated/payment-methods'
      path: '/payment-methods'
      fullPath: '/payment-methods'
      preLoaderRoute: typeof AuthenticatedPaymentMethodsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kyc': {
      id: '/_authenticated/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof AuthenticatedKycRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investment-requests': {
      id: '/_authenticated/investment-requests'
      path: '/investment-requests'
      fullPath: '/investment-requests'
      preLoaderRoute: typeof AuthenticatedInvestmentRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/convert': {
      id: '/_authenticated/convert'
      path: '/convert'
      fullPath: '/convert'
      preLoaderRoute: typeof AuthenticatedConvertRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificates': {
      id: '/_authenticated/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AuthenticatedCertificatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/asset-allocation': {
      id: '/_authenticated/asset-allocation'
      path: '/asset-allocation'
      fullPath: '/asset-allocation'
      preLoaderRoute: typeof AuthenticatedAssetAllocationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/broker/leads/$leadId': {
      id: '/broker/leads/$leadId'
      path: '/$leadId'
      fullPath: '/broker/leads/$leadId'
      preLoaderRoute: typeof BrokerLeadsLeadIdRouteImport
      parentRoute: typeof BrokerLeadsRoute
    }
    '/_authenticated/investment-requests/$id': {
      id: '/_authenticated/investment-requests/$id'
      path: '/$id'
      fullPath: '/investment-requests/$id'
      preLoaderRoute: typeof AuthenticatedInvestmentRequestsIdRouteImport
      parentRoute: typeof AuthenticatedInvestmentRequestsRoute
    }
    '/_authenticated/admin/withdrawals': {
      id: '/_authenticated/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AuthenticatedAdminWithdrawalsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/wallets': {
      id: '/_authenticated/admin/wallets'
      path: '/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AuthenticatedAdminWalletsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/transactions': {
      id: '/_authenticated/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AuthenticatedAdminTransactionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/sak-config': {
      id: '/_authenticated/admin/sak-config'
      path: '/sak-config'
      fullPath: '/admin/sak-config'
      preLoaderRoute: typeof AuthenticatedAdminSakConfigRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/projects': {
      id: '/_authenticated/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AuthenticatedAdminProjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/profits': {
      id: '/_authenticated/admin/profits'
      path: '/profits'
      fullPath: '/admin/profits'
      preLoaderRoute: typeof AuthenticatedAdminProfitsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/profit-history': {
      id: '/_authenticated/admin/profit-history'
      path: '/profit-history'
      fullPath: '/admin/profit-history'
      preLoaderRoute: typeof AuthenticatedAdminProfitHistoryRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/lands': {
      id: '/_authenticated/admin/lands'
      path: '/lands'
      fullPath: '/admin/lands'
      preLoaderRoute: typeof AuthenticatedAdminLandsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/kyc': {
      id: '/_authenticated/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AuthenticatedAdminKycRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/investors': {
      id: '/_authenticated/admin/investors'
      path: '/investors'
      fullPath: '/admin/investors'
      preLoaderRoute: typeof AuthenticatedAdminInvestorsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/investment-requests': {
      id: '/_authenticated/admin/investment-requests'
      path: '/investment-requests'
      fullPath: '/admin/investment-requests'
      preLoaderRoute: typeof AuthenticatedAdminInvestmentRequestsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/homepage': {
      id: '/_authenticated/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AuthenticatedAdminHomepageRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/gold': {
      id: '/_authenticated/admin/gold'
      path: '/gold'
      fullPath: '/admin/gold'
      preLoaderRoute: typeof AuthenticatedAdminGoldRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/deposits': {
      id: '/_authenticated/admin/deposits'
      path: '/deposits'
      fullPath: '/admin/deposits'
      preLoaderRoute: typeof AuthenticatedAdminDepositsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/countries': {
      id: '/_authenticated/admin/countries'
      path: '/countries'
      fullPath: '/admin/countries'
      preLoaderRoute: typeof AuthenticatedAdminCountriesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/commissions': {
      id: '/_authenticated/admin/commissions'
      path: '/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AuthenticatedAdminCommissionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cities': {
      id: '/_authenticated/admin/cities'
      path: '/cities'
      fullPath: '/admin/cities'
      preLoaderRoute: typeof AuthenticatedAdminCitiesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/brokers': {
      id: '/_authenticated/admin/brokers'
      path: '/brokers'
      fullPath: '/admin/brokers'
      preLoaderRoute: typeof AuthenticatedAdminBrokersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/broker-applications': {
      id: '/_authenticated/admin/broker-applications'
      path: '/broker-applications'
      fullPath: '/admin/broker-applications'
      preLoaderRoute: typeof AuthenticatedAdminBrokerApplicationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit-log': {
      id: '/_authenticated/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/asset-types': {
      id: '/_authenticated/admin/asset-types'
      path: '/asset-types'
      fullPath: '/admin/asset-types'
      preLoaderRoute: typeof AuthenticatedAdminAssetTypesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/investment-requests/$id/payment': {
      id: '/_authenticated/investment-requests/$id/payment'
      path: '/payment'
      fullPath: '/investment-requests/$id/payment'
      preLoaderRoute: typeof AuthenticatedInvestmentRequestsIdPaymentRouteImport
      parentRoute: typeof AuthenticatedInvestmentRequestsIdRoute
    }
    '/_authenticated/admin/investment-requests/$id': {
      id: '/_authenticated/admin/investment-requests/$id'
      path: '/$id'
      fullPath: '/admin/investment-requests/$id'
      preLoaderRoute: typeof AuthenticatedAdminInvestmentRequestsIdRouteImport
      parentRoute: typeof AuthenticatedAdminInvestmentRequestsRoute
    }
    '/_authenticated/admin/customers/$id': {
      id: '/_authenticated/admin/customers/$id'
      path: '/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AuthenticatedAdminCustomersIdRouteImport
      parentRoute: typeof AuthenticatedAdminCustomersRoute
    }
    '/_authenticated/admin/brokers/$id': {
      id: '/_authenticated/admin/brokers/$id'
      path: '/$id'
      fullPath: '/admin/brokers/$id'
      preLoaderRoute: typeof AuthenticatedAdminBrokersIdRouteImport
      parentRoute: typeof AuthenticatedAdminBrokersRoute
    }
  }
}

interface AuthenticatedAdminBrokersRouteChildren {
  AuthenticatedAdminBrokersIdRoute: typeof AuthenticatedAdminBrokersIdRoute
}

const AuthenticatedAdminBrokersRouteChildren: AuthenticatedAdminBrokersRouteChildren =
  {
    AuthenticatedAdminBrokersIdRoute: AuthenticatedAdminBrokersIdRoute,
  }

const AuthenticatedAdminBrokersRouteWithChildren =
  AuthenticatedAdminBrokersRoute._addFileChildren(
    AuthenticatedAdminBrokersRouteChildren,
  )

interface AuthenticatedAdminCustomersRouteChildren {
  AuthenticatedAdminCustomersIdRoute: typeof AuthenticatedAdminCustomersIdRoute
}

const AuthenticatedAdminCustomersRouteChildren: AuthenticatedAdminCustomersRouteChildren =
  {
    AuthenticatedAdminCustomersIdRoute: AuthenticatedAdminCustomersIdRoute,
  }

const AuthenticatedAdminCustomersRouteWithChildren =
  AuthenticatedAdminCustomersRoute._addFileChildren(
    AuthenticatedAdminCustomersRouteChildren,
  )

interface AuthenticatedAdminInvestmentRequestsRouteChildren {
  AuthenticatedAdminInvestmentRequestsIdRoute: typeof AuthenticatedAdminInvestmentRequestsIdRoute
}

const AuthenticatedAdminInvestmentRequestsRouteChildren: AuthenticatedAdminInvestmentRequestsRouteChildren =
  {
    AuthenticatedAdminInvestmentRequestsIdRoute:
      AuthenticatedAdminInvestmentRequestsIdRoute,
  }

const AuthenticatedAdminInvestmentRequestsRouteWithChildren =
  AuthenticatedAdminInvestmentRequestsRoute._addFileChildren(
    AuthenticatedAdminInvestmentRequestsRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAssetTypesRoute: typeof AuthenticatedAdminAssetTypesRoute
  AuthenticatedAdminAuditLogRoute: typeof AuthenticatedAdminAuditLogRoute
  AuthenticatedAdminBrokerApplicationsRoute: typeof AuthenticatedAdminBrokerApplicationsRoute
  AuthenticatedAdminBrokersRoute: typeof AuthenticatedAdminBrokersRouteWithChildren
  AuthenticatedAdminCitiesRoute: typeof AuthenticatedAdminCitiesRoute
  AuthenticatedAdminCommissionsRoute: typeof AuthenticatedAdminCommissionsRoute
  AuthenticatedAdminCountriesRoute: typeof AuthenticatedAdminCountriesRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRouteWithChildren
  AuthenticatedAdminDepositsRoute: typeof AuthenticatedAdminDepositsRoute
  AuthenticatedAdminGoldRoute: typeof AuthenticatedAdminGoldRoute
  AuthenticatedAdminHomepageRoute: typeof AuthenticatedAdminHomepageRoute
  AuthenticatedAdminInvestmentRequestsRoute: typeof AuthenticatedAdminInvestmentRequestsRouteWithChildren
  AuthenticatedAdminInvestorsRoute: typeof AuthenticatedAdminInvestorsRoute
  AuthenticatedAdminKycRoute: typeof AuthenticatedAdminKycRoute
  AuthenticatedAdminLandsRoute: typeof AuthenticatedAdminLandsRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminProfitHistoryRoute: typeof AuthenticatedAdminProfitHistoryRoute
  AuthenticatedAdminProfitsRoute: typeof AuthenticatedAdminProfitsRoute
  AuthenticatedAdminProjectsRoute: typeof AuthenticatedAdminProjectsRoute
  AuthenticatedAdminSakConfigRoute: typeof AuthenticatedAdminSakConfigRoute
  AuthenticatedAdminTransactionsRoute: typeof AuthenticatedAdminTransactionsRoute
  AuthenticatedAdminWalletsRoute: typeof AuthenticatedAdminWalletsRoute
  AuthenticatedAdminWithdrawalsRoute: typeof AuthenticatedAdminWithdrawalsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAssetTypesRoute: AuthenticatedAdminAssetTypesRoute,
    AuthenticatedAdminAuditLogRoute: AuthenticatedAdminAuditLogRoute,
    AuthenticatedAdminBrokerApplicationsRoute:
      AuthenticatedAdminBrokerApplicationsRoute,
    AuthenticatedAdminBrokersRoute: AuthenticatedAdminBrokersRouteWithChildren,
    AuthenticatedAdminCitiesRoute: AuthenticatedAdminCitiesRoute,
    AuthenticatedAdminCommissionsRoute: AuthenticatedAdminCommissionsRoute,
    AuthenticatedAdminCountriesRoute: AuthenticatedAdminCountriesRoute,
    AuthenticatedAdminCustomersRoute:
      AuthenticatedAdminCustomersRouteWithChildren,
    AuthenticatedAdminDepositsRoute: AuthenticatedAdminDepositsRoute,
    AuthenticatedAdminGoldRoute: AuthenticatedAdminGoldRoute,
    AuthenticatedAdminHomepageRoute: AuthenticatedAdminHomepageRoute,
    AuthenticatedAdminInvestmentRequestsRoute:
      AuthenticatedAdminInvestmentRequestsRouteWithChildren,
    AuthenticatedAdminInvestorsRoute: AuthenticatedAdminInvestorsRoute,
    AuthenticatedAdminKycRoute: AuthenticatedAdminKycRoute,
    AuthenticatedAdminLandsRoute: AuthenticatedAdminLandsRoute,
    AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
    AuthenticatedAdminProfitHistoryRoute: AuthenticatedAdminProfitHistoryRoute,
    AuthenticatedAdminProfitsRoute: AuthenticatedAdminProfitsRoute,
    AuthenticatedAdminProjectsRoute: AuthenticatedAdminProjectsRoute,
    AuthenticatedAdminSakConfigRoute: AuthenticatedAdminSakConfigRoute,
    AuthenticatedAdminTransactionsRoute: AuthenticatedAdminTransactionsRoute,
    AuthenticatedAdminWalletsRoute: AuthenticatedAdminWalletsRoute,
    AuthenticatedAdminWithdrawalsRoute: AuthenticatedAdminWithdrawalsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedInvestmentRequestsIdRouteChildren {
  AuthenticatedInvestmentRequestsIdPaymentRoute: typeof AuthenticatedInvestmentRequestsIdPaymentRoute
}

const AuthenticatedInvestmentRequestsIdRouteChildren: AuthenticatedInvestmentRequestsIdRouteChildren =
  {
    AuthenticatedInvestmentRequestsIdPaymentRoute:
      AuthenticatedInvestmentRequestsIdPaymentRoute,
  }

const AuthenticatedInvestmentRequestsIdRouteWithChildren =
  AuthenticatedInvestmentRequestsIdRoute._addFileChildren(
    AuthenticatedInvestmentRequestsIdRouteChildren,
  )

interface AuthenticatedInvestmentRequestsRouteChildren {
  AuthenticatedInvestmentRequestsIdRoute: typeof AuthenticatedInvestmentRequestsIdRouteWithChildren
}

const AuthenticatedInvestmentRequestsRouteChildren: AuthenticatedInvestmentRequestsRouteChildren =
  {
    AuthenticatedInvestmentRequestsIdRoute:
      AuthenticatedInvestmentRequestsIdRouteWithChildren,
  }

const AuthenticatedInvestmentRequestsRouteWithChildren =
  AuthenticatedInvestmentRequestsRoute._addFileChildren(
    AuthenticatedInvestmentRequestsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAssetAllocationRoute: typeof AuthenticatedAssetAllocationRoute
  AuthenticatedCertificatesRoute: typeof AuthenticatedCertificatesRoute
  AuthenticatedConvertRoute: typeof AuthenticatedConvertRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInvestmentRequestsRoute: typeof AuthenticatedInvestmentRequestsRouteWithChildren
  AuthenticatedKycRoute: typeof AuthenticatedKycRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPaymentMethodsRoute: typeof AuthenticatedPaymentMethodsRoute
  AuthenticatedPerformanceRoute: typeof AuthenticatedPerformanceRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
  AuthenticatedProfitsRoute: typeof AuthenticatedProfitsRoute
  AuthenticatedRealAssetsRoute: typeof AuthenticatedRealAssetsRoute
  AuthenticatedSakBalanceRoute: typeof AuthenticatedSakBalanceRoute
  AuthenticatedSakGoldRoute: typeof AuthenticatedSakGoldRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAssetAllocationRoute: AuthenticatedAssetAllocationRoute,
  AuthenticatedCertificatesRoute: AuthenticatedCertificatesRoute,
  AuthenticatedConvertRoute: AuthenticatedConvertRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInvestmentRequestsRoute:
    AuthenticatedInvestmentRequestsRouteWithChildren,
  AuthenticatedKycRoute: AuthenticatedKycRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPaymentMethodsRoute: AuthenticatedPaymentMethodsRoute,
  AuthenticatedPerformanceRoute: AuthenticatedPerformanceRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
  AuthenticatedProfitsRoute: AuthenticatedProfitsRoute,
  AuthenticatedRealAssetsRoute: AuthenticatedRealAssetsRoute,
  AuthenticatedSakBalanceRoute: AuthenticatedSakBalanceRoute,
  AuthenticatedSakGoldRoute: AuthenticatedSakGoldRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BrokerLeadsRouteChildren {
  BrokerLeadsLeadIdRoute: typeof BrokerLeadsLeadIdRoute
}

const BrokerLeadsRouteChildren: BrokerLeadsRouteChildren = {
  BrokerLeadsLeadIdRoute: BrokerLeadsLeadIdRoute,
}

const BrokerLeadsRouteWithChildren = BrokerLeadsRoute._addFileChildren(
  BrokerLeadsRouteChildren,
)

interface BrokerRouteRouteChildren {
  BrokerAnalyticsRoute: typeof BrokerAnalyticsRoute
  BrokerBookingsRoute: typeof BrokerBookingsRoute
  BrokerClientsRoute: typeof BrokerClientsRoute
  BrokerCommissionsRoute: typeof BrokerCommissionsRoute
  BrokerInvestmentRequestsRoute: typeof BrokerInvestmentRequestsRoute
  BrokerLeadsRoute: typeof BrokerLeadsRouteWithChildren
  BrokerProfileRoute: typeof BrokerProfileRoute
  BrokerReferralsRoute: typeof BrokerReferralsRoute
  BrokerViewingsRoute: typeof BrokerViewingsRoute
  BrokerIndexRoute: typeof BrokerIndexRoute
}

const BrokerRouteRouteChildren: BrokerRouteRouteChildren = {
  BrokerAnalyticsRoute: BrokerAnalyticsRoute,
  BrokerBookingsRoute: BrokerBookingsRoute,
  BrokerClientsRoute: BrokerClientsRoute,
  BrokerCommissionsRoute: BrokerCommissionsRoute,
  BrokerInvestmentRequestsRoute: BrokerInvestmentRequestsRoute,
  BrokerLeadsRoute: BrokerLeadsRouteWithChildren,
  BrokerProfileRoute: BrokerProfileRoute,
  BrokerReferralsRoute: BrokerReferralsRoute,
  BrokerViewingsRoute: BrokerViewingsRoute,
  BrokerIndexRoute: BrokerIndexRoute,
}

const BrokerRouteRouteWithChildren = BrokerRouteRoute._addFileChildren(
  BrokerRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  BrokerRouteRoute: BrokerRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ProjectsRoute: ProjectsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AssetsLandIdRoute: AssetsLandIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
